import Head from 'next/head'
import Image from 'next/image'
import { LoginComponent } from '../components/ui/login-btn'
import { Title } from '../components/Title'

import { Header } from '../components/layout/Header'
import Link from 'next/link'
import { Slider } from '../components/Slider'

import heroIMG from '../../public/images/desktop-images/landing/produce-background-cropped.png'

export default function Home() {
   return (
      <div className="">
         <Head>
            <title>Terra</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className="bg-white mt-20 md:mt-0 flex flex-col items-center">
            <div className="max-w-[1440px] w-full">
               <div className="terra-landing-hero w-full md:min-h-[80vh] bg-contain bg-right-bottom bg-no-repeat flex flex-col justify-center border-2 border-secondary">
                  <div className="border-2 border-error md:top-[-200px] lg:top-0 3xl:top-[-250px] relative px-6 md:px-[84px] w-full lg:w-3/5">
                     <Title
                        variant="h1"
                        className="text-primary md:text-[56px]"
                     >
                        Replenish the earth, one action at a time.
                     </Title>
                     <p className="md:text-xl">
                        From farm to table, we want all produce to be loved and
                        used.
                     </p>
                  </div>
               </div>
               <Slider />
            </div>

            <div className="mt-32 mb-48">
               <LoginComponent />
            </div>
         </main>
      </div>
   )
}

Home.getLayout = function getLayout(page) {
   return (
      <>
         <Header />
         {page}
      </>
   )
}
